version: '3'
services:
  php:
    image: php:7.4.3-fpm
    # build:
    #   context: .
    volumes:
      # - ./src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      # - ./src/www.conf:/etc/php/7.4/fpm/php-fpm.d/www.conf
      - ./app:/var/www/html
    # ports:
    #   - 8080:8080
  composer:
    image: composer
    volumes:
        - ./app:/app
    command: install
  web:
    image: nginx
    volumes:
        - ./src/default.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html
    ports:
        - "8080:8080"
    restart: always